encoding: utf-8

# Site settings
title: ChaoticWeg
email: shawn@chaoticweg.cc
description: Shawn Lutch
url: "https://chaoticweg.cc"
twitter_username: ChaoticWeg
github_username:  ChaoticWeg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
